language: python
dist: xenial
python:
  - 3.8

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      install:
        - pip install -r requirements.txt
      script:
        - flake8 scraper tests
    - stage: test
      install:
        - pip install -r requirements.txt
      script:
        - python -m pytest tests/